#SimpleCore made by JuanantonioVYT for MegaHost communitty

Join-Message: "§8[§b+§8]§b{player}"

Quit-Message: "§8[§c-§8]§c{player}"

#Permissions Message Confjg

NotPermissions: "§cYou do not have permissions to use"

#Hub Nessages Config

Hub-Message: "Volvistes al lobby {player}"
Hub-Title: "Joined Lobby"

#Menu Games Command Config

CommandForm1: "tranferserver modalidad1.ddns.net:25595"
CommandForm2: "tranferserver modalidad1.ddns.net:25595"
CommandForm3: "tranferserver modalidad1.ddns.net:25595"
CommandForm3: "tranferserver modalidad4.ddns.net:25595"
CommandForm5: "tranferserver modalidad5.ddns.net:25595"
CommandForm6: "tranferserver modalidad6.ddns.net:25595"

#Menu Games Config

GameTitle: "Modalidades"
GameInfo: "Elije que modalidad que deseas jugar"

GameForm1: "modalidad1"
GameForm2: "modalidad2"
GameForm3: "modalidad3"
GameForm4: "modalidad4"
GameForm5: "modalidad5"
GameForm6: "modalidad6"

#Menu Cosmetics Config

CosmeticTitle: "Cosmetics"
CosmeticInfo: "Cosmeticos solo para VIP"

CosmeticForm1: "Fly"
CosmeticForm2: "Size"

#Messages Fly Config

FlyMessageTrue: "Fly §bactivado"
FlyTitleTrue: "FLY §cON"

FlyMessageFalse: "Fly desactivado"
FlyTitleFalse: "FLY OFF"

#Menu Fly Config

FlyTitle: "¿Fly ON & Fly OFF?"
FlyInfo: "Fly for VIP"

FlyForm1: "FLY ON"
FlyForm2: "FLY OFF"

#Message Size Config

SizeMessageNormal: "Size normal"
SizeTitleNormal: "Su tamaño es normal"

SizeMessageMedium: "Size medium"
SizeTitleMedium: "Su tamaño es mediano"

SizeMessageBig: "Size big"
SizeTitleBig: "Su tamaño es grande"

#Menu Size Config

SizeTitle: "SizeMode"
SizeInfo: "Aumenta el tamaño de tu skin"

SizeForm1: "Size Normal"
SizeForm2: "Size Mediano"
SizeForm3: "Size Grande"

#Menu Info Config

InfoTitle: "Informacion"
Info: "Information"

#Soon More Updates
