#SimpleCore made by JuanantonioVYT for MegaHost communitty

Join-Message: "§8[§b+§8]§b{player}"

Quit-Message: "§8[§c-§8]§c{player}"

#Permissions Message Confjg

NotPermissions: "§cYou do not have permissions to use"

#Menu Games Config

GameTitle: "§bGames"
GameInfo: "§fChoose the minigame you wanna play!"

GameForm1: "§aSky§7Wars"
GameForm2: "§aBed§eWars"
GameForm3: "§aMurder§cMystery"
GameForm4: "§9The§cBridge"
GameForm5: "§eF§bF§aA"
GameForm6: "§eFi§ast"

#Menu Games Command Config

CommandForm1: "tranferserver modalidad1.ddns.net:25595"
CommandForm2: "tranferserver modalidad1.ddns.net:25595"
CommandForm3: "tranferserver modalidad1.ddns.net:25595"
CommandForm3: "tranferserver modalidad4.ddns.net:25595"
CommandForm5: "tranferserver modalidad5.ddns.net:25595"
CommandForm6: "tranferserver modalidad6.ddns.net:25595"


#Menu Fly Config

FlyTitle: "¿Fly ON & Fly OFF?"
FlyInfo: "Fly for VIP"

FlyForm1: "FLY ON"
FlyForm2: "FLY OFF"

#Message Size Config

SizeMessageNormal: "Size Normal!"

SizeMessageMedium: "Size Medium!"

SizeMessageBig: "Size Big!"

#Menu Size Config

SizeTitle: "SizeMode"
SizeInfo: "Aumenta el tamaño de tu skin"

SizeForm1: "Size Normal"
SizeForm2: "Size Mediano"
SizeForm3: "Size Grande"

#Menu Info Config

InfoTitle: "Informacion"
Info: "Information"

#Soon More Updates
